name: Build Gardenlinux Images for Tags

on:
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "1443.18"
          - "1443.19"
          - "1443.20"
          - "1592.10"
          - "1592.11"
          - "1592.12"
          - "1592.13"
          - "1592.14"
          - "1592.15"
          - "1592.4"
          - "1592.5"
          - "1592.6"
          - "1592.7"
          - "1592.8"
          - "1592.9"
          - "1877.0"
          - "1877.1"
          - "1877.2"
          - "1877.3"
          - "1877.4"
          - "1877.5"
          - "1877.6"
          - "1877.7"
          - "1877.8"
          - "main"
        image:
          - "ali"
          - "aws"
          - "azure"
          - "gcp"
          - "openstack"
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Clone gardenlinux repo
        run: |
          git clone https://github.com/gardenlinux/gardenlinux.git
          cd gardenlinux

          if [ "${{ matrix.tag }}" != "main" ]; then
            git fetch --tags
            git checkout tags/${{ matrix.tag }}
          fi

      - name: Build image
        run: |
          # for versions that start with 14 or 15, download the keyring from main branch
          if [[ "${{ matrix.tag }}" =~ ^14|^15 ]]; then
            rm keyring.gpg
            curl -L -o keyring.gpg https://github.com/gardenlinux/gardenlinux/raw/refs/heads/main/keyring.gpg
          fi
          ./build --container-image ghcr.io/gardenlinux/builder:04e9781b20811f22d51aa0edcfa03d2ad1a9c4df "${{ matrix.image }}-gardener_prod"

      - name: Upload sourcemanifest artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: sourcemanifest-${{ matrix.tag }}-${{ matrix.image }}
          path: gardenlinux/.build/*.sourcemanifest
          include-hidden-files: true

  collect-sourcemanifests:
    runs-on: ubuntu-latest
    needs: build-images
    steps:
      - name: Download all sourcemanifest artifacts
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          path: all_sourcemanifests
      - name: Move all sourcemanifests to top level
        run: |
          mkdir flat_sourcemanifests
          find all_sourcemanifests -type f -name '*.sourcemanifest' -exec mv {} flat_sourcemanifests/ \;
      - name: Zip all sourcemanifests (no subdirectories)
        run: |
          cd flat_sourcemanifests
          zip ../all-sourcemanifests.zip ./*
      - name: Upload all sourcemanifests zip
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: all-sourcemanifests
          path: all-sourcemanifests.zip
